# Generated by Django 4.2.30 on 2026-06-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="chapter_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="upload",
            name="chapter_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="upload",
            name="college",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="upload",
            name="course_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
