# Generated by Django 4.2.30 on 2026-06-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_discountcode_order_discount_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="delete_after",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
