# Generated by Django 4.2.30 on 2026-07-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_upload_delete_after"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="code",
            field=models.CharField(blank=True, db_index=True, max_length=12),
        ),
    ]
