# Generated by Django 4.2.30 on 2026-07-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_downloadlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="failed_login_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="login_locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
