# Generated by Django 4.2.30 on 2026-09-11 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_user_failed_login_attempts_user_login_locked_until"),
    ]

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=60, unique=True)),
                ("position", models.PositiveIntegerField(unique=True)),
                ("is_summer", models.BooleanField(default=False)),
                ("starts_on", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="access",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="access_grants",
                to="api.semester",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="api.semester",
            ),
        ),
    ]
