# Generated by Django 4.2.30 on 2026-09-13 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_seed_semesters"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadlog",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="downloads",
                to="api.semester",
            ),
        ),
    ]
