# Generated by Django 4.2.30 on 2026-09-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_backfill_downloadlog_semester"),
    ]

    operations = [
        migrations.AddField(
            model_name="access",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True
            ),
        ),
    ]
