# Generated by Django 4.2.30 on 2026-09-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_backfill_note_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountcode",
            name="allowed_emails",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="amount",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="kind",
            field=models.CharField(
                choices=[("percent", "Percentage off"), ("amount", "Fixed amount off")],
                default="percent",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="min_subtotal",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="percent",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
