# Generated by Django 4.2.30 on 2026-10-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_backfill_order_discount_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="name_style",
            field=models.CharField(
                choices=[
                    ("full", "Full name"),
                    ("first", "First name only"),
                    ("anonymous", "No name"),
                ],
                default="full",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="rating",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="review_prompt_dismissed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
